### ISSUE TITLE
Add Captcha Config Requirements to Readme

### ISSUE THREAD

**Issue by sipple** [pgharts/trusty-rad-social-extension#1]
We need a standard way to have people add captcha config keys to their project when using rad social. Probably in a captcha_config.rb initializer, or the like.

**Comment by brittanyjspringer** [comment]
This is completed on CD.org by adding in a new recaptcha.rb Initializer. Will do the same for Festivity. Since we use Recaptcha on CD.org for other things, it makes sense to keep the env vars on there.
