### ISSUE TITLE
Email Share: Recaptcha window is taller than email window

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-rad-social-extension#15]
The new recaptcha window is taller than the email form window. Increase the height of the email form to accommodate. 

![6-8-2016 11-49-09 am](https://cloud.githubusercontent.com/assets/177947/15900885/199875b8-2d6f-11e6-9243-74c4e3438c4d.png)

**Comment by danigirl329** [comment]
This is a Convoy setting that needs fixed
